### PR TITLE
CMake install + find_package support

### PR DESCRIPTION
**Pull request by pezcode**
This PR lets you install liblava as well as find and link it from CMake. It's an alternative to adding it as a project subdirectory and allows you to compile and use specific versions of lava. Inspired by https://github.com/liblava/liblava/issues/3.

Tested on Win 10 (MSVC) + WSL (G++ 8)

# Installing

**Command line:**
```bash
mkdir build & cd build
cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=../lava-install ..
cmake --build . --target install
```

# Linking

**CMakeLists.txt:**
```cmake
find_package(lava 0.5.1 REQUIRED)

add_executable(test main.cpp)
target_link_libraries(test lava::app)
```

**Command line:**
```bash
mkdir build & cd build
cmake -D CMAKE_BUILD_TYPE=Release -D lava_DIR=path/to/lava-install/lib/cmake/lava ..
cmake --build .
```

## Notes

- Since all of the libraries are bundled, external headers must be copied as well. To not pollute /usr/include during a standard install, they are installed to include/liblava/ext/
- Not all external headers are installed, only the ones that are actually linked to from lava includes. This could be changed if you think it makes sense to use 'private' libraries like glfw (the lines are commented out at `install(DIRECTORY ...)`).
- ~~CMake doesn't want to export library aliases, so all targets are exported as lava.core instead of lava::core. This could be worked around by defining aliases again in *LavaConfig.cmake.in* or by defining targets as core, util, etc. and defining a namespace "lava::" at `install(EXPORT ...)`~~
- CMake doesn't like exporting interface sources so I removed them from lava.core for now. ~~Not sure if there's a workaround; an empty static library with no cpp files didn't work (linker error for missing .lib that was never produced)~~ Possible workaround below.

### CODE REVIEW

**Comment by pezcode** [comment]
Looks like it works on Ubuntu \🤠/

Another note on the interface sources: I just realized that was the reason I had liblava .hpp files in all my Visual Studio projects. It doesn't really serve a purpose, but if you want it for documentation purposes, something like the following works:

```cmake
file(WRITE ${CMAKE_CURRENT_BINARY_DIR}/empty.cpp "")

add_library(lava.core STATIC
        ${CMAKE_CURRENT_BINARY_DIR}/empty.cpp
        ${LIBLAVA_DIR}/core/data.hpp
        ${LIBLAVA_DIR}/core/id.hpp
        ${LIBLAVA_DIR}/core/math.hpp
        ${LIBLAVA_DIR}/core/time.hpp
        ${LIBLAVA_DIR}/core/types.hpp
        ${LIBLAVA_DIR}/core/version.hpp
        )
```

**Comment by TheLavaBlock** [comment]
Wow. That looks great. :clap:

I will try it out. And let's wait for @julianxhokaxhiu feedback before merging it.

**Comment by julianxhokaxhiu** [comment]
Amazing! I will try it ASAP. Can you please assign this issue to me so I do not forget? Thank you to both in advance!

**Comment by TheLavaBlock** [comment]
Had to fix the install config name because find_package() is looking for lower case.

**Comment by julianxhokaxhiu** [comment]
I do have an issue building it on my side:

```
fatal error C1083: Cannot open include file: 'spdlog/sinks/stdout_color_sinks.h': No such file or directory
```

I did clone your fork recursively, checked out `cmake-install` branch and then run your build instructions. Am I missing something?

**Comment by pezcode** [comment]
I'm guessing this is git not checking out the updated spdlog submodule.
Try `git submodule update`

**Comment by julianxhokaxhiu** [comment]
You're right, I forgot to update submodules when I did checkout your branch. All good, now it builds fine and it produces the required install artifacts! Well done and thank you :)

@TheLavaBlocks LGTM

**Comment by TheLavaBlock** [comment]
Good stuff. Thank you @pezcode 

Btw: I will add **Installing** and **Linking** info to the documentation shortly.

**Pull request merged**
