### PR TITLE
fix synchronization with more than two backbuffers

### LINKED ISSUE #20: [error] create instance
Linux (Arch)
When trying to run any example or the template I get the following terminal output:

[2020-03-21 18:35:03.200] [lava] [info] >>> 2020 preview / 0.5.0 - lava triangle / 0.5.0 - Mar 21 2020 18:06:29
[2020-03-21 18:35:03.201] [lava] [info] cmd ./lava-triangle
[2020-03-21 18:35:03.201] [lava] [debug] glfw 3.4.0 X11 GLX EGL OSMesa clock_gettime evdev
[2020-03-21 18:35:03.282] [lava] [info] vulkan 1.2.133
[2020-03-21 18:35:03.283] [lava] [error] create instance param
[2020-03-21 18:35:03.283] [lava] [error] create instance

Am I missing dependencies or how do I get a more verbos output?

### PR DESCRIPTION
**Pull request by underdoeg**
Buffers are not necessarily acquired in order so by simply waiting on current_sync it is not 100% certain that the actual frame is done. This PR creates a semaphore lookup table for the current frame index and waits on that as well. Normally one of these fences will already be unlocked. This also allows for any number of semaphores. fixes #20

### CODE REVIEW

**Comment by underdoeg** [comment]
So the proprietary nvidia driver on arch does not offer ```VK_PRESENT_MODE_MAILBOX_KHR``` for me. But ```VK_PRESENT_MODE_FIFO_KHR``` introduces lag and is not really what I would expect when not setting v-sync. So IMO it makes sense to just fall back to immediate mode instead.

**Comment by TheLavaBlock** [comment]
I will do some testing and analysis on this problem, maybe I can reproduce it somehow.

**Comment by TheLavaBlock** [comment]
🚀 Thanks. I haven't been able to reproduce it yet but I' ll take a closer look at it later. 👀

**Comment by underdoeg** [comment]
thanks

**Pull request merged**
