### PR TITLE
New demo: light

### PR DESCRIPTION
**Pull request by pezcode**
Small demo that showcases how to render to an offscreen framebuffer and sample from it. It's doing 'deferred shading', but the actual lighting pass is just done in a single fullscreen draw. A proper renderer would be rendering light geometry impostors or use tiling/clustering, but this is a demo so 🤷 

Lighting code uses basic normal mapping and PBR shading, most of it adopted from old code of mine. References/sources are provided where possible. I also did some very minor cleanup/convenience fixes I found useful while working on this, feel free to cherry pick whatever you like/don't like.

And a screenshot:
screenshot

It's default res unlike the other demo screenshots, so feel free to take a better one.

### CODE REVIEW

**Comment by pezcode** [comment]
CI seems to die on `index` being ambiguous, not entirely sure what's happening there. I've only tested this on MSVC 2019 :eyes:

**Comment by pezcode** [comment]
Also, feel free to use other models/textures or change the lights if this is too bland. I just wanted to keep things minimal while programming.

**Comment by TheLavaBlock** [comment]
Excellent! 👍  LGTM

I would like to undo cc7009f and set the related call in the example for the frame index to `0`

And yeah, this index build error is weird. I put the `lava` namespace in front of it.

I'll take a closer look at the code over the next few days, maybe I'll have another idea or two. For example, we could offer a few parameters for the lights with `imgui` - Let's see, if you think of something, let me know 💡 

Will do the PR first and then adjust some things...

**Comment by pezcode** [comment]
Some UI-controllable settings would be nice indeed. Random ideas:
- roughness multiplier
- diffuse color (current just white)
- metallic
- toggle normal mapping
- light color(s)
- light position(s), maybe along a predefined line/arc to make it simpler

A proper mesh might be useful as well, since I realized that my hack for inverting normals for double-sided materials breaks the normal-mapping code because of flipped UVs.

**Pull request merged**
